// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-next';
import type { GetInputsData, GetInputsResponse, GetMeasurementsData, GetMeasurementsResponse, GetForecastPointsData, GetForecastPointsResponse, PutForecastData, PutForecastResponse, PutResultsData, PutResultsResponse, PostAdvanceData, PostAdvanceResponse, GetNameData, GetNameResponse, GetStepData, GetStepResponse, PutStepData, PutStepResponse, GetScenarioData, GetScenarioResponse, GetKpiData, GetKpiResponse, PutInitializeData, PutInitializeResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get metadata for inputs
 * Returns metadata for input signals.
 */
export const getInputs = <ThrowOnError extends boolean = false>(options?: Options<GetInputsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetInputsResponse, unknown, ThrowOnError>({
        url: '/inputs',
        ...options
    });
};

/**
 * Get metadata for measurements
 * Returns metadata for measurement signals.
 */
export const getMeasurements = <ThrowOnError extends boolean = false>(options?: Options<GetMeasurementsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeasurementsResponse, unknown, ThrowOnError>({
        url: '/measurements',
        ...options
    });
};

/**
 * Get metadata for forecast points
 * Returns metadata for forecast point signals.
 */
export const getForecastPoints = <ThrowOnError extends boolean = false>(options?: Options<GetForecastPointsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetForecastPointsResponse, unknown, ThrowOnError>({
        url: '/forecast_points',
        ...options
    });
};

/**
 * Submit a forecast query
 * Sends a ForecastQuery payload and returns a TimeSeries response.
 */
export const putForecast = <ThrowOnError extends boolean = false>(options: Options<PutForecastData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutForecastResponse, unknown, ThrowOnError>({
        url: '/forecast',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Submit a results query
 * Sends a ResultsQuery payload and returns a TimeSeries response.
 */
export const putResults = <ThrowOnError extends boolean = false>(options: Options<PutResultsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutResultsResponse, unknown, ThrowOnError>({
        url: '/results',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Advance the simulation
 * Advances the simulation with optional input overwrites. The payload can include input values and activation flags for overwriting.
 */
export const postAdvance = <ThrowOnError extends boolean = false>(options?: Options<PostAdvanceData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAdvanceResponse, unknown, ThrowOnError>({
        url: '/advance',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get the test case name
 * Returns the loaded test case name.
 */
export const getName = <ThrowOnError extends boolean = false>(options?: Options<GetNameData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetNameResponse, unknown, ThrowOnError>({
        url: '/name',
        ...options
    });
};

/**
 * Get the simulation time step
 * Returns the time step used in the simulation.
 */
export const getStep = <ThrowOnError extends boolean = false>(options?: Options<GetStepData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetStepResponse, unknown, ThrowOnError>({
        url: '/step',
        ...options
    });
};

/**
 * Set the simulation time step
 * Sets the time step used in the simulation.
 */
export const putStep = <ThrowOnError extends boolean = false>(options: Options<PutStepData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutStepResponse, unknown, ThrowOnError>({
        url: '/step',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get the current scenario description
 * Returns a description of the current scenario.
 */
export const getScenario = <ThrowOnError extends boolean = false>(options?: Options<GetScenarioData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetScenarioResponse, unknown, ThrowOnError>({
        url: '/scenario',
        ...options
    });
};

/**
 * Get the Key Performance Indicators (KPIs)
 * Returns the KPIs as calculated by the emulator.
 */
export const getKpi = <ThrowOnError extends boolean = false>(options?: Options<GetKpiData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetKpiResponse, unknown, ThrowOnError>({
        url: '/kpi',
        ...options
    });
};

/**
 * Initialize the simulation
 * Initializes the simulation with a start time and warmup period.
 */
export const putInitialize = <ThrowOnError extends boolean = false>(options: Options<PutInitializeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutInitializeResponse, unknown, ThrowOnError>({
        url: '/initialize',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};