// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-next';
import type { GetInputsByTestidData, GetInputsByTestidResponse, GetMeasurementsByTestidData, GetMeasurementsByTestidResponse, GetForecastPointsByTestidData, GetForecastPointsByTestidResponse, PutForecastByTestidData, PutForecastByTestidResponse, PutResultsByTestidData, PutResultsByTestidResponse, PostAdvanceByTestidData, PostAdvanceByTestidResponse, GetNameByTestidData, GetNameByTestidResponse, GetStepByTestidData, GetStepByTestidResponse, PutStepByTestidData, PutStepByTestidResponse, GetScenarioByTestidData, GetScenarioByTestidResponse, GetKpiByTestidData, GetKpiByTestidResponse, PutInitializeByTestidData, PutInitializeByTestidResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get metadata for inputs
 * Returns metadata for input signals.
 */
export const getInputsByTestid = <ThrowOnError extends boolean = false>(options: Options<GetInputsByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetInputsByTestidResponse, unknown, ThrowOnError>({
        url: '/inputs/{testid}',
        ...options
    });
};

/**
 * Get metadata for measurements
 * Returns metadata for measurement signals.
 */
export const getMeasurementsByTestid = <ThrowOnError extends boolean = false>(options: Options<GetMeasurementsByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetMeasurementsByTestidResponse, unknown, ThrowOnError>({
        url: '/measurements/{testid}',
        ...options
    });
};

/**
 * Get metadata for forecast points
 * Returns metadata for forecast point signals.
 */
export const getForecastPointsByTestid = <ThrowOnError extends boolean = false>(options: Options<GetForecastPointsByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetForecastPointsByTestidResponse, unknown, ThrowOnError>({
        url: '/forecast_points/{testid}',
        ...options
    });
};

/**
 * Submit a forecast query
 * Sends a ForecastQuery payload and returns a TimeSeries response.
 */
export const putForecastByTestid = <ThrowOnError extends boolean = false>(options: Options<PutForecastByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutForecastByTestidResponse, unknown, ThrowOnError>({
        url: '/forecast/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Submit a results query
 * Sends a ResultsQuery payload and returns a TimeSeries response.
 */
export const putResultsByTestid = <ThrowOnError extends boolean = false>(options: Options<PutResultsByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutResultsByTestidResponse, unknown, ThrowOnError>({
        url: '/results/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Advance the simulation
 * Advances the simulation with optional input overwrites. The payload can include input values and activation flags for overwriting.
 */
export const postAdvanceByTestid = <ThrowOnError extends boolean = false>(options: Options<PostAdvanceByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostAdvanceByTestidResponse, unknown, ThrowOnError>({
        url: '/advance/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get the test case name
 * Returns the loaded test case name.
 */
export const getNameByTestid = <ThrowOnError extends boolean = false>(options: Options<GetNameByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetNameByTestidResponse, unknown, ThrowOnError>({
        url: '/name/{testid}',
        ...options
    });
};

/**
 * Get the simulation time step
 * Returns the time step used in the simulation.
 */
export const getStepByTestid = <ThrowOnError extends boolean = false>(options: Options<GetStepByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetStepByTestidResponse, unknown, ThrowOnError>({
        url: '/step/{testid}',
        ...options
    });
};

/**
 * Set the simulation time step
 * Sets the time step used in the simulation.
 */
export const putStepByTestid = <ThrowOnError extends boolean = false>(options: Options<PutStepByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutStepByTestidResponse, unknown, ThrowOnError>({
        url: '/step/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get the current scenario description
 * Returns a description of the current scenario.
 */
export const getScenarioByTestid = <ThrowOnError extends boolean = false>(options: Options<GetScenarioByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetScenarioByTestidResponse, unknown, ThrowOnError>({
        url: '/scenario/{testid}',
        ...options
    });
};

/**
 * Get the Key Performance Indicators (KPIs)
 * Returns the KPIs as calculated by the emulator.
 */
export const getKpiByTestid = <ThrowOnError extends boolean = false>(options: Options<GetKpiByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetKpiByTestidResponse, unknown, ThrowOnError>({
        url: '/kpi/{testid}',
        ...options
    });
};

/**
 * Initialize the simulation
 * Initializes the simulation with a start time and warmup period.
 */
export const putInitializeByTestid = <ThrowOnError extends boolean = false>(options: Options<PutInitializeByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutInitializeByTestidResponse, unknown, ThrowOnError>({
        url: '/initialize/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};