// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-next';
import type { GetTestcasesData, GetTestcasesResponse, PostTestcasesByTestcaseNameSelectData, PostTestcasesByTestcaseNameSelectResponse, PutInitializeByTestidData, PutInitializeByTestidResponse, GetNameByTestidData, GetNameByTestidResponse, GetStatusByTestidData, GetStatusByTestidResponse, PutStopByTestidData, PutStopByTestidResponse, GetVersionData, GetVersionResponse, GetInputsByTestidData, GetInputsByTestidResponse, GetMeasurementsByTestidData, GetMeasurementsByTestidResponse, GetForecastPointsByTestidData, GetForecastPointsByTestidResponse, GetScenarioByTestidData, GetScenarioByTestidResponse, PutScenarioByTestidData, PutScenarioByTestidResponse, GetStepByTestidData, GetStepByTestidResponse, PutStepByTestidData, PutStepByTestidResponse, PutForecastByTestidData, PutForecastByTestidResponse, PutResultsByTestidData, PutResultsByTestidResponse, GetKpiByTestidData, GetKpiByTestidResponse, PostAdvanceByTestidData, PostAdvanceByTestidResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List available test cases
 * Returns a list of available IBPSA BOPTEST test cases (official).
 */
export const getTestcases = <ThrowOnError extends boolean = false>(options?: Options<GetTestcasesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTestcasesResponse, unknown, ThrowOnError>({
        url: '/testcases',
        ...options
    });
};

/**
 * Select a test case and start a new test
 * Selects an IBPSA BOPTEST test case and begins a new test. Returns a testid (UUID) required by other APIs.
 */
export const postTestcasesByTestcaseNameSelect = <ThrowOnError extends boolean = false>(options: Options<PostTestcasesByTestcaseNameSelectData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostTestcasesByTestcaseNameSelectResponse, unknown, ThrowOnError>({
        url: '/testcases/{testcase_name}/select',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Initialize the simulation
 * Initialize simulation to a start time using a warmup period (also resets history and KPI calculations).
 */
export const putInitializeByTestid = <ThrowOnError extends boolean = false>(options: Options<PutInitializeByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutInitializeByTestidResponse, unknown, ThrowOnError>({
        url: '/initialize/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get the test case name
 * Returns the loaded test case name.
 */
export const getNameByTestid = <ThrowOnError extends boolean = false>(options: Options<GetNameByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetNameByTestidResponse, unknown, ThrowOnError>({
        url: '/name/{testid}',
        ...options
    });
};

/**
 * Get test status
 * Returns the current status of the test (e.g. Running, Queued).
 */
export const getStatusByTestid = <ThrowOnError extends boolean = false>(options: Options<GetStatusByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetStatusByTestidResponse, unknown, ThrowOnError>({
        url: '/status/{testid}',
        ...options
    });
};

/**
 * Stop a queued or running test
 * Stops a queued or running test. Use when freeing workers or to terminate a running test.
 */
export const putStopByTestid = <ThrowOnError extends boolean = false>(options: Options<PutStopByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutStopByTestidResponse, unknown, ThrowOnError>({
        url: '/stop/{testid}',
        ...options
    });
};

/**
 * Get BOPTEST version
 * Returns the BOPTEST version for the running test.
 */
export const getVersion = <ThrowOnError extends boolean = false>(options?: Options<GetVersionData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetVersionResponse, unknown, ThrowOnError>({
        url: '/version',
        ...options
    });
};

/**
 * Get metadata for inputs
 * Returns available control signal input point names (u) and metadata.
 */
export const getInputsByTestid = <ThrowOnError extends boolean = false>(options: Options<GetInputsByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetInputsByTestidResponse, unknown, ThrowOnError>({
        url: '/inputs/{testid}',
        ...options
    });
};

/**
 * Get metadata for measurements
 * Returns available sensor signal output point names (y) and metadata.
 */
export const getMeasurementsByTestid = <ThrowOnError extends boolean = false>(options: Options<GetMeasurementsByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetMeasurementsByTestidResponse, unknown, ThrowOnError>({
        url: '/measurements/{testid}',
        ...options
    });
};

/**
 * Get metadata for forecast points
 * Returns available forecast point names and metadata.
 */
export const getForecastPointsByTestid = <ThrowOnError extends boolean = false>(options: Options<GetForecastPointsByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetForecastPointsByTestidResponse, unknown, ThrowOnError>({
        url: '/forecast_points/{testid}',
        ...options
    });
};

/**
 * Get the current scenario setup
 * Returns a description of the current scenario.
 */
export const getScenarioByTestid = <ThrowOnError extends boolean = false>(options: Options<GetScenarioByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetScenarioByTestidResponse, unknown, ThrowOnError>({
        url: '/scenario/{testid}',
        ...options
    });
};

/**
 * Set a test scenario
 * Set the scenario for the running test. Optional properties may trigger an initialization (see README).
 * Typically, the supported scenario settings include:
 * * electricity_price: "constant" or "dynamic" or "highly_dynamic"
 * * time_period: "typical_heat_day" or "peak_heat_day"
 * * temperature_uncertainty: *null* or "low" or "medium" or "high"
 * * solar_uncertainty: *null* or "low" or "medium" or "high"
 * * seed: *int*
 *
 * However, this is partly test case specific. See the test case documentation for supported scenarios.
 *
 */
export const putScenarioByTestid = <ThrowOnError extends boolean = false>(options: Options<PutScenarioByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutScenarioByTestidResponse, unknown, ThrowOnError>({
        url: '/scenario/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get the control time step
 * Returns the time step used for control.
 */
export const getStepByTestid = <ThrowOnError extends boolean = false>(options: Options<GetStepByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetStepByTestidResponse, unknown, ThrowOnError>({
        url: '/step/{testid}',
        ...options
    });
};

/**
 * Set the control time step
 * Sets the time step used for control.
 */
export const putStepByTestid = <ThrowOnError extends boolean = false>(options: Options<PutStepByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutStepByTestidResponse, unknown, ThrowOnError>({
        url: '/step/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Query forecasts.
 * Returns boundary condition forecasts from current time.
 */
export const putForecastByTestid = <ThrowOnError extends boolean = false>(options: Options<PutForecastByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutForecastByTestidResponse, unknown, ThrowOnError>({
        url: '/forecast/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Query results.
 * Returns simulation data for the given point names over a time period.
 * Data for control input points will be the values used for simulation,
 * meaning embedded default control if not overwritten or user-specified
 * value if overwritten.
 *
 */
export const putResultsByTestid = <ThrowOnError extends boolean = false>(options: Options<PutResultsByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutResultsByTestidResponse, unknown, ThrowOnError>({
        url: '/results/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get KPIs for a running test
 * Receive KPI values for the running test. Calculated from start time and do not include warmup periods.
 */
export const getKpiByTestid = <ThrowOnError extends boolean = false>(options: Options<GetKpiByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetKpiByTestidResponse, unknown, ThrowOnError>({
        url: '/kpi/{testid}',
        ...options
    });
};

/**
 * Advance the simulation one control step with optional control input overrides.
 * Advance simulation one control step with optional control input(s) and receive measurements.
 * If specified, control input value(s) will be constant over the control step.
 * Use <input_name_u> to specify value and corresponding <input_name_activate> to enable value
 * overwrite for the input.
 *
 */
export const postAdvanceByTestid = <ThrowOnError extends boolean = false>(options: Options<PostAdvanceByTestidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostAdvanceByTestidResponse, unknown, ThrowOnError>({
        url: '/advance/{testid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};