// This file is auto-generated by @hey-api/openapi-ts

export type BoundedSignalMeta = {
    /**
     * Description of the signal.
     */
    Description?: string;
    /**
     * Maximum value of the signal.
     */
    Maximum?: number | null;
    /**
     * Minimum value of the signal.
     */
    Minimum?: number | null;
    /**
     * Unit of the signal.
     */
    Unit?: string | null;
};

export type SignalMeta = {
    /**
     * Description of the signal.
     */
    Description?: string;
    /**
     * Unit of the signal.
     */
    Unit?: string | null;
};

export type BoundedSignalMetaResponse = {
    [key: string]: BoundedSignalMeta;
};

export type SignalMetaResponse = {
    [key: string]: SignalMeta;
};

export type ForecastQuery = {
    /**
     * List of point names.
     */
    point_names?: Array<string>;
    /**
     * Forecast horizon in seconds.
     */
    horizon?: number;
    /**
     * Time interval between forecast points in seconds.
     */
    interval?: number;
};

export type ResultsQuery = {
    /**
     * List of point names.
     */
    point_names?: Array<string>;
    /**
     * Start time of the results query (epoch time).
     */
    start_time?: number;
    /**
     * Final time of the results query (epoch time).
     */
    final_time?: number;
};

export type TimeSeries = {
    [key: string]: Array<number>;
};

export type StandardResponse = {
    /**
     * A message describing the response.
     */
    message?: string;
    /**
     * The response payload.
     */
    payload?: {
        [key: string]: unknown;
    };
    /**
     * HTTP status code.
     */
    status?: number;
};

/**
 * The UUID of the test case.
 */
export type TestId = string;

export type GetInputsByTestidData = {
    body?: never;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/inputs/{testid}';
};

export type GetInputsByTestidResponses = {
    /**
     * Successful response with metadata for inputs.
     */
    200: {
        message?: string;
        payload?: BoundedSignalMetaResponse;
        status?: number;
    };
};

export type GetInputsByTestidResponse = GetInputsByTestidResponses[keyof GetInputsByTestidResponses];

export type GetMeasurementsByTestidData = {
    body?: never;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/measurements/{testid}';
};

export type GetMeasurementsByTestidResponses = {
    /**
     * Successful response with metadata for measurements.
     */
    200: {
        message?: string;
        payload?: BoundedSignalMetaResponse;
        status?: number;
    };
};

export type GetMeasurementsByTestidResponse = GetMeasurementsByTestidResponses[keyof GetMeasurementsByTestidResponses];

export type GetForecastPointsByTestidData = {
    body?: never;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/forecast_points/{testid}';
};

export type GetForecastPointsByTestidResponses = {
    /**
     * Successful response with metadata for forecast points.
     */
    200: {
        message?: string;
        payload?: SignalMetaResponse;
        status?: number;
    };
};

export type GetForecastPointsByTestidResponse = GetForecastPointsByTestidResponses[keyof GetForecastPointsByTestidResponses];

export type PutForecastByTestidData = {
    body: ForecastQuery;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/forecast/{testid}';
};

export type PutForecastByTestidResponses = {
    /**
     * Successful response with forecast time series.
     */
    200: {
        message?: string;
        payload?: TimeSeries;
        status?: number;
    };
};

export type PutForecastByTestidResponse = PutForecastByTestidResponses[keyof PutForecastByTestidResponses];

export type PutResultsByTestidData = {
    body: ResultsQuery;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/results/{testid}';
};

export type PutResultsByTestidResponses = {
    /**
     * Successful response with results time series.
     */
    200: {
        message?: string;
        payload?: TimeSeries;
        status?: number;
    };
};

export type PutResultsByTestidResponse = PutResultsByTestidResponses[keyof PutResultsByTestidResponses];

export type PostAdvanceByTestidData = {
    body?: {
        [key: string]: number | 0 | 1;
    };
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/advance/{testid}';
};

export type PostAdvanceByTestidResponses = {
    /**
     * Successful response with simulation advancement results.
     */
    200: {
        message?: string;
        payload?: {
            [key: string]: number;
        };
        status?: number;
    };
};

export type PostAdvanceByTestidResponse = PostAdvanceByTestidResponses[keyof PostAdvanceByTestidResponses];

export type GetNameByTestidData = {
    body?: never;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/name/{testid}';
};

export type GetNameByTestidResponses = {
    /**
     * Successful response with the test case name.
     */
    200: {
        message?: string;
        /**
         * The payload containing the test case name.
         */
        payload?: {
            /**
             * The name of the test case.
             */
            name?: string;
        };
        status?: number;
    };
};

export type GetNameByTestidResponse = GetNameByTestidResponses[keyof GetNameByTestidResponses];

export type GetStepByTestidData = {
    body?: never;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/step/{testid}';
};

export type GetStepByTestidResponses = {
    /**
     * Successful response with the time step.
     */
    200: {
        message?: string;
        /**
         * The time step used in the simulation.
         */
        payload?: number;
        status?: number;
    };
};

export type GetStepByTestidResponse = GetStepByTestidResponses[keyof GetStepByTestidResponses];

export type PutStepByTestidData = {
    body: {
        /**
         * The new time step to set for the simulation.
         */
        step?: number;
    };
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/step/{testid}';
};

export type PutStepByTestidResponses = {
    /**
     * Successful response indicating the time step was updated.
     */
    200: {
        message?: string;
        /**
         * Confirmation message.
         */
        payload?: string;
        status?: number;
    };
};

export type PutStepByTestidResponse = PutStepByTestidResponses[keyof PutStepByTestidResponses];

export type GetScenarioByTestidData = {
    body?: never;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/scenario/{testid}';
};

export type GetScenarioByTestidResponses = {
    /**
     * Successful response with the scenario description.
     */
    200: {
        message?: string;
        payload?: {
            [key: string]: string;
        };
        status?: number;
    };
};

export type GetScenarioByTestidResponse = GetScenarioByTestidResponses[keyof GetScenarioByTestidResponses];

export type GetKpiByTestidData = {
    body?: never;
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/kpi/{testid}';
};

export type GetKpiByTestidResponses = {
    /**
     * Successful response with the KPIs.
     */
    200: {
        message?: string;
        payload?: {
            [key: string]: number;
        };
        status?: number;
    };
};

export type GetKpiByTestidResponse = GetKpiByTestidResponses[keyof GetKpiByTestidResponses];

export type PutInitializeByTestidData = {
    body: {
        /**
         * The start time of the simulation (epoch time).
         */
        start_time?: number;
        /**
         * The warmup period for the simulation in seconds.
         */
        warmup_period?: number;
    };
    path: {
        /**
         * The UUID of the test case.
         */
        testid: string;
    };
    query?: never;
    url: '/initialize/{testid}';
};

export type PutInitializeByTestidResponses = {
    /**
     * Successful response indicating the simulation was initialized.
     */
    200: {
        message?: string;
        /**
         * Confirmation message.
         */
        payload?: string;
        status?: number;
    };
};

export type PutInitializeByTestidResponse = PutInitializeByTestidResponses[keyof PutInitializeByTestidResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost' | 'http://api.boptest.net' | (string & {});
};