// This file is auto-generated by @hey-api/openapi-ts

export type BoundedSignalMeta = {
    /**
     * Description of the signal.
     */
    Description?: string;
    /**
     * Maximum value of the signal.
     */
    Maximum?: number | null;
    /**
     * Minimum value of the signal.
     */
    Minimum?: number | null;
    /**
     * Unit of the signal.
     */
    Unit?: string | null;
};

export type SignalMeta = {
    /**
     * Description of the signal.
     */
    Description?: string;
    /**
     * Unit of the signal.
     */
    Unit?: string | null;
};

export type BoundedSignalMetaResponse = {
    [key: string]: BoundedSignalMeta;
};

export type SignalMetaResponse = {
    [key: string]: SignalMeta;
};

export type ForecastQuery = {
    /**
     * List of point names.
     */
    point_names?: Array<string>;
    /**
     * Forecast horizon in seconds.
     */
    horizon?: number;
    /**
     * Time interval between forecast points in seconds.
     */
    interval?: number;
};

export type ResultsQuery = {
    /**
     * List of point names.
     */
    point_names?: Array<string>;
    /**
     * Start time of the results query (epoch time).
     */
    start_time?: number;
    /**
     * Final time of the results query (epoch time).
     */
    final_time?: number;
};

export type TimeSeries = {
    [key: string]: Array<number>;
};

export type StandardResponse = {
    /**
     * A message describing the response.
     */
    message?: string;
    /**
     * The response payload.
     */
    payload?: {
        [key: string]: unknown;
    };
    /**
     * HTTP status code.
     */
    status?: number;
};

export type GetInputsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inputs';
};

export type GetInputsResponses = {
    /**
     * Successful response with metadata for inputs.
     */
    200: {
        message?: string;
        payload?: BoundedSignalMetaResponse;
        status?: number;
    };
};

export type GetInputsResponse = GetInputsResponses[keyof GetInputsResponses];

export type GetMeasurementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/measurements';
};

export type GetMeasurementsResponses = {
    /**
     * Successful response with metadata for measurements.
     */
    200: {
        message?: string;
        payload?: BoundedSignalMetaResponse;
        status?: number;
    };
};

export type GetMeasurementsResponse = GetMeasurementsResponses[keyof GetMeasurementsResponses];

export type GetForecastPointsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/forecast_points';
};

export type GetForecastPointsResponses = {
    /**
     * Successful response with metadata for forecast points.
     */
    200: {
        message?: string;
        payload?: SignalMetaResponse;
        status?: number;
    };
};

export type GetForecastPointsResponse = GetForecastPointsResponses[keyof GetForecastPointsResponses];

export type PutForecastData = {
    body: ForecastQuery;
    path?: never;
    query?: never;
    url: '/forecast';
};

export type PutForecastResponses = {
    /**
     * Successful response with forecast time series.
     */
    200: {
        message?: string;
        payload?: TimeSeries;
        status?: number;
    };
};

export type PutForecastResponse = PutForecastResponses[keyof PutForecastResponses];

export type PutResultsData = {
    body: ResultsQuery;
    path?: never;
    query?: never;
    url: '/results';
};

export type PutResultsResponses = {
    /**
     * Successful response with results time series.
     */
    200: {
        message?: string;
        payload?: TimeSeries;
        status?: number;
    };
};

export type PutResultsResponse = PutResultsResponses[keyof PutResultsResponses];

export type PostAdvanceData = {
    body?: {
        [key: string]: number | 0 | 1;
    };
    path?: never;
    query?: never;
    url: '/advance';
};

export type PostAdvanceResponses = {
    /**
     * Successful response with simulation advancement results.
     */
    200: {
        message?: string;
        payload?: {
            [key: string]: number;
        };
        status?: number;
    };
};

export type PostAdvanceResponse = PostAdvanceResponses[keyof PostAdvanceResponses];

export type GetStepData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/step';
};

export type GetStepResponses = {
    /**
     * Successful response with the time step.
     */
    200: {
        message?: string;
        /**
         * The time step used in the simulation.
         */
        payload?: number;
        status?: number;
    };
};

export type GetStepResponse = GetStepResponses[keyof GetStepResponses];

export type PutStepData = {
    body: {
        /**
         * The new time step to set for the simulation.
         */
        step?: number;
    };
    path?: never;
    query?: never;
    url: '/step';
};

export type PutStepResponses = {
    /**
     * Successful response indicating the time step was updated.
     */
    200: {
        message?: string;
        /**
         * Confirmation message.
         */
        payload?: string;
        status?: number;
    };
};

export type PutStepResponse = PutStepResponses[keyof PutStepResponses];

export type GetScenarioData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/scenario';
};

export type GetScenarioResponses = {
    /**
     * Successful response with the scenario description.
     */
    200: {
        message?: string;
        payload?: {
            [key: string]: string;
        };
        status?: number;
    };
};

export type GetScenarioResponse = GetScenarioResponses[keyof GetScenarioResponses];

export type GetKpiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/kpi';
};

export type GetKpiResponses = {
    /**
     * Successful response with the KPIs.
     */
    200: {
        message?: string;
        payload?: {
            [key: string]: number;
        };
        status?: number;
    };
};

export type GetKpiResponse = GetKpiResponses[keyof GetKpiResponses];

export type PutInitializeData = {
    body: {
        /**
         * The start time of the simulation (epoch time).
         */
        start_time?: number;
        /**
         * The warmup period for the simulation in seconds.
         */
        warmup_period?: number;
    };
    path?: never;
    query?: never;
    url: '/initialize';
};

export type PutInitializeResponses = {
    /**
     * Successful response indicating the simulation was initialized.
     */
    200: {
        message?: string;
        /**
         * Confirmation message.
         */
        payload?: string;
        status?: number;
    };
};

export type PutInitializeResponse = PutInitializeResponses[keyof PutInitializeResponses];

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:5000' | (string & {});
};